// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v4.23.3
// source: ClientRequest-TCP.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "ClientRequest.TCP";

export interface LoginRequest {
  username: string;
  password?: Uint8Array | undefined;
}

export interface FindMatchRequest {
  sessionId: Uint8Array;
}

export interface ChatMessageRequest {
  sessionId: Uint8Array;
  chatMessage: string;
}

function createBaseLoginRequest(): LoginRequest {
  return { username: "", password: undefined };
}

export const LoginRequest = {
  encode(message: LoginRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== undefined) {
      writer.uint32(18).bytes(message.password);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.password = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? bytesFromBase64(object.password) : undefined,
    };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== undefined) {
      obj.password = base64FromBytes(message.password);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.username = object.username ?? "";
    message.password = object.password ?? undefined;
    return message;
  },
};

function createBaseFindMatchRequest(): FindMatchRequest {
  return { sessionId: new Uint8Array(0) };
}

export const FindMatchRequest = {
  encode(message: FindMatchRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId.length !== 0) {
      writer.uint32(10).bytes(message.sessionId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): FindMatchRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindMatchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindMatchRequest {
    return { sessionId: isSet(object.sessionId) ? bytesFromBase64(object.sessionId) : new Uint8Array(0) };
  },

  toJSON(message: FindMatchRequest): unknown {
    const obj: any = {};
    if (message.sessionId.length !== 0) {
      obj.sessionId = base64FromBytes(message.sessionId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindMatchRequest>, I>>(base?: I): FindMatchRequest {
    return FindMatchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindMatchRequest>, I>>(object: I): FindMatchRequest {
    const message = createBaseFindMatchRequest();
    message.sessionId = object.sessionId ?? new Uint8Array(0);
    return message;
  },
};

function createBaseChatMessageRequest(): ChatMessageRequest {
  return { sessionId: new Uint8Array(0), chatMessage: "" };
}

export const ChatMessageRequest = {
  encode(message: ChatMessageRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId.length !== 0) {
      writer.uint32(10).bytes(message.sessionId);
    }
    if (message.chatMessage !== "") {
      writer.uint32(18).string(message.chatMessage);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ChatMessageRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.bytes();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.chatMessage = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatMessageRequest {
    return {
      sessionId: isSet(object.sessionId) ? bytesFromBase64(object.sessionId) : new Uint8Array(0),
      chatMessage: isSet(object.chatMessage) ? globalThis.String(object.chatMessage) : "",
    };
  },

  toJSON(message: ChatMessageRequest): unknown {
    const obj: any = {};
    if (message.sessionId.length !== 0) {
      obj.sessionId = base64FromBytes(message.sessionId);
    }
    if (message.chatMessage !== "") {
      obj.chatMessage = message.chatMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatMessageRequest>, I>>(base?: I): ChatMessageRequest {
    return ChatMessageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessageRequest>, I>>(object: I): ChatMessageRequest {
    const message = createBaseChatMessageRequest();
    message.sessionId = object.sessionId ?? new Uint8Array(0);
    message.chatMessage = object.chatMessage ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
